//housing
module.exports =[
    {
        id:'27',
        type:'CensusMultiStackedLineChart',
        censusKey:['B25004'],
        VacantHousing:true,
        colorRange:[],
        layout:{
            w:4,
            h:14,
            x:0,
            y:82,
            static:false
        }

    },
    {
        id:'28',
        type:'CensusStackedBarChart',
        censusKey:['B25118'],
        TenureHouseholdIncome:true,
        colorRange:[],
        layout:{
            static: true,
            h:17,
            w:11,
            x:0,
            y:0
        }
    },
    {
        id:'29',
        type:'CensusBarChart',
        censusKey:['B25087'],
        housingUnitsMortgageCosts: true,
        colorRange:[],
        layout:{
            static:true,
            h:14,
            w:10,
            x:0,
            y:0
        }
    },
    {
        id:'30',
        type:'CensusBarChart',
        censusKey:['B25087'],
        housingUnitsNoMortgageCosts: true,
        colorRange:[],
        layout:{
            static:true,
            h:14,
            w:10,
            x:0,
            y:0
        }
    }
]