module.exports = [
   {
      "id":"1",
      "type":"CensusStatBox",
      "censusKey":"B01003_001E",
      "year":"2017",
      compareYear: 2016,
      "title": "Population",
      "layout":{
         "w":2,
         "h":5,
         "x":0,
         "y":0,
         "i":"1",
         "static":false
      },
      "geoids":[
         "36001"
      ]
   },
   {
      "id":"2",
      "type":"CensusStatBox",
      "censusKey":[
         "B01002"
      ],
      "year":[
         "2017"
      ],
      "demographics":true,
      "colorRange":[

      ],
      "layout":{
         "w":2,
         "h":5,
         "x":2,
         "y":0,
         "i":"2",
         "static":false
      },
      "geoid":[
         "36001"
      ]
   },
   {
      "id":"3",
      "type":"CensusPieChart",
      "censusKey":[
         "B02001"
      ],
      "year":[
         "2017"
      ],
      "single":true,
      "colorRange":[

      ],
      "layout":{
         "w":4,
         "h":5,
         "x":4,
         "y":0,
         "i":"3",
         "static":false
      },
      "geoid":[
         "36001"
      ]
   },
   {
      "id":"4",
      "type":"CensusLineChart",
      "censusKey":[
         "B19013"
      ],
      "colorRange":[

      ],
      "layout":{
         "w":10,
         "h":13,
         "x":2,
         "y":5,
         "i":"4",
         "static":false
      },
      "geoid":[
         "36001"
      ]
   },
   {
      "id":"5",
      "type":"CensusStatBox",
      "censusKey":[
         "B19013"
      ],
      "amount":true,
      "colorRange":[

      ],
      "layout":{
         "w":2,
         "h":13,
         "x":0,
         "y":5,
         "i":"5",
         "static":false
      },
      "geoid":[
         "36001"
      ]
   },
   {
      "id":"6",
      "type":"CensusStatBox",
      "censusKey":[
         "B17001"
      ],
      "poverty":true,
      "colorRange":[

      ],
      "layout":{
         "w":2,
         "h":13,
         "x":0,
         "y":18,
         "i":"6",
         "static":false
      },
      "geoid":[
         "36001"
      ]
   },
   {
      "id":"7",
      "type":"CensusLineChart",
      "censusKey":[
         "B17001"
      ],
      "PovertyPopulationBySex":true,
      "colorRange":[

      ],
      "layout":{
         "w":10,
         "h":13,
         "x":2,
         "y":18,
         "i":"7",
         "static":false
      },
      "geoid":[
         "36001"
      ]
   },
   {
      "id":"8",
      "type":"CensusStatBox",
      "censusKey":[
         "B25002"
      ],
      "housing":true,
      "colorRange":[

      ],
      "layout":{
         "w":2,
         "h":13,
         "x":0,
         "y":31,
         "i":"8",
         "static":false
      },
      "geoid":[
         "36001"
      ]
   },
   {
      "id":"9",
      "type":"CensusStackedLineChart",
      "censusKey":[
         "B25002"
      ],
      "colorRange":[

      ],
      "layout":{
         "w":10,
         "h":13,
         "x":2,
         "y":31,
         "i":"9",
         "static":false
      },
      "geoid":[
         "36001"
      ]
   },
   {
      "id":"10",
      "type":"CensusStatBox",
      "censusKey":[
         "B15003"
      ],
      "education":true,
      "colorRange":[

      ],
      "layout":{
         "w":2,
         "h":13,
         "x":0,
         "y":44,
         "i":"10",
         "static":false
      },
      "geoid":[
         "36001"
      ]
   },
   {
      "id":"11",
      "type":"CensusMultiStackedLineChart",
      "censusKey":[
         "B15003"
      ],
      "colorRange":[

      ],
      "education":true,
      "layout":{
         "w":10,
         "h":13,
         "x":2,
         "y":44,
         "i":"11",
         "static":false
      },
      "geoid":[
         "36001"
      ]
   },
   {
      "id":"12",
      "type":"CensusGroupedBarChart",
      "censusKey":[
         "B23008"
      ],
      "compareGeoid":[
         "36"
      ],
      "colorRange":[

      ],
      "layout":{
         "w":12,
         "h":13,
         "x":0,
         "y":57,
         "i":"12",
         "static":false
      },
      "geoid":[
         "36001"
      ]
   }
]